baseURL = "https://mwhickson.github.io/blog"
cleanDestinationDir = true
locale = "en-us"
publishDir = "docs"
title = "Matthew Hickson's Blog"

theme = "hugo-flex"

[params]
    color = "#660000"
    footer = "Copyright 2026, Matthew Hickson. All rights reserved."
    summaries = true

[menus]
    [[menus.main]]
        name = "Posts"
        pageRef = "/post"
        weight = 10

    [[menus.main]]
        name = "Lists"
        pageRef = "/lists"
        weight = 20

    [[menus.main]]
        name = "Tags"
        pageRef = "/tags"
        weight = 30
